export const routes = {
    BASIC_URL: "http://localhost:8080/",
    BASIC_PATH: "api/",
    LOGIN_URL: "login",
    REGISTRATION_URL: "sign-up",
    REFRESH_TOKEN: "token/refresh",
    PROFILE_DATA: "profile/get/",
    DELETE_USER: "user/delete/",
    UPDATE_USER: "user/update/",
    ALL_USERS: "user/users",
    ALL_BOOKS: "book/books",
    ALL_AUTHORS: "author/authors",
    ALL_CATEGORIES: "category/categories",
    BOOK_THE_BOOK: "book/bookTheBook",
    GET_BOOKS_BY_CRITERIA: "book/find_books_by_criteria",
    GET_BOOKS_BY_CATEGORY: "book/bookByCategory",
    GET_BOOKS_BY_AUTHOR: "book/bookByAuthor",
    GIVE_THE_BOOK: "book/giveTheBook",
    RETURN_THE_BOOK: "book/returnTheBook",
    CLIENT_DATA: "user/find-by-email/"
}